### PR TITLE
add click events to show active console links

### PR DESCRIPTION
**Pull request by RyanBeiden**
All events to change the active nav link are now stored in the `clickEvents.js` file

### CODE REVIEW

**Review by JeremiahV93 — COMMENTED** [review]
The misspelling in the JSON file, did you import it to firebase as well?
I think the loading bar should be bigger, a little hard to read
image

**Comment by ryanbeiden** [comment]
I did import the changes to firebase as well! So that should be good to go.

And I’ll make that bar bigger! Thanks for the suggestion Jeremiah 🙌🏼

**Comment by ryanbeiden** [comment]
Needs more work.

**Review by JeremiahV93 — APPROVED** [review]
Ready to go

**Comment by ryanbeiden** [comment]
See #44

**Pull request closed without merging**
